### ISSUE TITLE
Error building on Arch Linux

### ISSUE THREAD

**Issue by ghost** [eafer/linux-apfs-oot#5]
Just upgraded my system (i'm using Arch Linux), and got an error with this module: 
```
==> dkms install --no-depmod -m linux-apfs -v 0.1 -k 5.8.0-arch1-1
Error! Bad return status for module build on kernel: 5.8.0-arch1-1 (x86_64)
Consult /var/lib/dkms/linux-apfs/0.1/build/make.log for more information.
==> Warning, `dkms install --no-depmod -m linux-apfs -v 0.1 -k 5.8.0-arch1-1' returned 10
```
Make.log is this:
```
DKMS make.log for linux-apfs-0.1 for kernel 5.8.0-arch1-1 (x86_64)
Tue Aug 4 13:26:17 EDT 2020
make: Entering directory '/usr/lib/modules/5.8.0-arch1-1/build'
AR /var/lib/dkms/linux-apfs/0.1/build/built-in.a
CC [M] /var/lib/dkms/linux-apfs/0.1/build/btree.o
CC [M] /var/lib/dkms/linux-apfs/0.1/build/dir.o
CC [M] /var/lib/dkms/linux-apfs/0.1/build/extents.o
CC [M] /var/lib/dkms/linux-apfs/0.1/build/file.o
CC [M] /var/lib/dkms/linux-apfs/0.1/build/inode.o
CC [M] /var/lib/dkms/linux-apfs/0.1/build/key.o
CC [M] /var/lib/dkms/linux-apfs/0.1/build/message.o
CC [M] /var/lib/dkms/linux-apfs/0.1/build/namei.o
/var/lib/dkms/linux-apfs/0.1/build/inode.c: In function 'apfs_readpages':
/var/lib/dkms/linux-apfs/0.1/build/inode.c:31:9: error: implicit declaration of function 'mpage_readpages'; did you mean 'mpage_readpage'? [-Werror=implicit-function-declaration]
31 | return mpage_readpages(mapping, pages, nr_pages, apfs_get_block);
  |         ^~~~~~~~~~~~~~~
  |         mpage_readpage
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:281: /var/lib/dkms/linux-apfs/0.1/build/inode.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:1756: /var/lib/dkms/linux-apfs/0.1/build] Error 2
make: Leaving directory '/usr/lib/modules/5.8.0-arch1-1/build'
```
Why is this happening?

**Comment by eafer** [comment]
On Tue, Aug 04, 2020 at 10:52:24AM -0700, binex wrote:
> Why is this happening?

The internal apis of the kernel are not stable, so out-of-tree modules such
as this will break every few releases. In this case, as you figured out
yourself already, it's because they got rid of mpage_readpages().

Your patch looks good, thank you. It has a lot of whitespace damage though,
so I'll commit it myself instead of taking the pull request. Do you want to
give me your real name and email so that I can credit you as the author in
the standard way, or do you prefer "binex"?

**Comment by ghost** [comment]
Yeah, I figured it out after a few hours. And I don't know why GitHub did that, because the patch I sent to the AUR link didn't have all that whitespace change. I did copy it directly from my terminal rather than from a normal text editor though, so that might be the reason why, after all, whitespace can be weird in some terminals.

I guess you can just credit me with the name "sperg" and my main email is roachh@protonmail.com. If you'd like, just use "binex", either is fine!

**Comment by eafer** [comment]
> And I don't know why GitHub did that, because the patch I sent to the AUR link didn't have all that whitespace change. I did copy it directly from my terminal rather than from a normal text editor though, so that might me the reason why.

Yes, copy-paste from a terminal usually turns your tabs into spaces. To
avoid this, you can just push or mail patches from git.

> I guess you can just credit me with the name "sperg" and my main email is roachh@protonmail.com. If you'd like, just use "binex", either is fine!

Done. Thanks again!

**Comment by HLFH** [comment]
I can build and install [this software](https://aur.archlinux.org/packages/linux-apfs-dkms-git/) or [this one](https://aur.archlinux.org/packages/linux-apfs-git/) on ArchLinux.

But I have the *structure needs cleaning* error when I mount the APFS partition.

> ➜  ~ mount /dev/nvme0n1p2 /mnt/apfs
> mount: /mnt/apfs: échec de l’appel système mount(2) : La structure a besoin d'un nettoyage.
> 

My ArchLinux file system is using BTRFS.

> ➜  ~ uname -r
> 5.10.4-arch2-1

**Comment by binex-dsk** [comment]
@HLFH already was fixed. Forgot to close

**Comment by eafer** [comment]
The issue with the build was solved already. I just forgot to close it
because I don't usually log in to github. Your problem is probably
unrelated.

> But I have the *structure needs cleaning* error when I mount the APFS partition.

Do you see any more details in the logs?

**Comment by HLFH** [comment]
I don't know where to look for the logs related to *linux-apfs-oot*. I'll probably go on macOS, and test * fsck_apfs* or Disk Utility repair feature, to see if it solves the *structure needs cleaning* issue.

**Comment by eafer** [comment]
On Fri, Jan 08, 2021 at 11:09:18AM -0800, HLFH wrote:
> I don't know where to look for the logs related to *linux-apfs-oot*.

You just need to run dmesg (as root), right after trying to mount the
filesystem.

> I'll probably go on macOS, and test * fsck_apfs* or Disk Utility repair feature, to see if it solves the *structure needs cleaning* issue.

I doubt that you have any real corruption. This module is a very incomplete
implementation of APFS, and the message probably just means that your
filesystem has a feature we don't know about.

**Comment by HLFH** [comment]
@eafer 

You can close this issue since it is apparently solved.

My issue is related to https://github.com/linux-apfs/linux-apfs-oot/issues/3.

I have:
> [243915.516458] APFS (nvme0n1p2): this module is read-only
> [243915.538507] APFS (nvme0n1p2): bad node in block 0x6b8
> [243915.538719] APFS (nvme0n1p2): unable to read catalog root node

**Comment by ghost** [comment]
> You can close this issue since it is apparently solved.

hi
